### ISSUE TITLE
Bug: if using the --filter parameter on strings containing a space its not working

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonodectl#61]
## Bug Description

when filtering for strings containing a `space` filter is not working properly ..., maybe this is a bug also in geonode backend, but i guess rather in geonodectl

**Comment by mwallschlaeger** [comment]
bug is part of geonodectl, tested it using the browser and it works

**Comment by mwallschlaeger** [comment]
after further digging into this, the problem isn't the space, its case sensivity. Therefore, forcing lower case for all keywords need to be impl. into the agrovoc-importer tool: ref https://github.com/GeoNodeUserGroup-DE/geonode-agrovoc-importer/issues/3

**Comment by specka** [comment]
Should be tested by Xenia after installing the geonode-ctl

**Comment by specka** [comment]
I tried to use geonodectl with command 'geonodectl dataset list' but an error 500 occured (see https://github.com/zalf-rdm/geonode/issues/132)

**Comment by specka** [comment]
@mwallschlaeger: I still need some more information to really test this issue. what kind of command should I use in the API/geonodectl? I don't have a clue, what was the problem based on the original description here of this bug.

**Comment by mwallschlaeger** [comment]
the bad response you @specka noticed was related to a somehow corrupted dataset inside the zalf-geonode installation. 

related logs:
```
nternal Server Error: /api/v2/datasets/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/bases.py", line 23, in wrapper
    self._resettable_cached_properties[func.__name__] = func(self)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/serializers.py", line 91, in data
    data = super(DynamicListSerializer, self).data
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/serializers.py", line 70, in to_representation
    return [self.child.to_representation(item) for item in iterable]
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/serializers.py", line 70, in <listcomp>
    return [self.child.to_representation(item) for item in iterable]
  File "/usr/src/geonode/./geonode/base/api/serializers.py", line 104, in to_representation
    data = super(ResourceBaseToRepresentationSerializerMixin, self).to_representation(instance)
  File "/usr/src/geonode/./geonode/base/api/serializers.py", line 88, in to_representation
    data = super().to_representation(instance)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/serializers.py", line 704, in to_representation
    self.obj_cache[pk] = self._to_representation(instance)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/serializers.py", line 654, in _to_representation
    representation = self._faster_to_representation(instance)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/serializers.py", line 640, in _faster_to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.10/dist-packages/dynamic_rest/fields/fields.py", line 319, in to_representation
    return serializer.to_representation(instance)
  File "/usr/src/geonode/./geonode/base/api/serializers.py", line 1054, in to_representation
    "title": f"{'>>>' if instance.is_target else '<<<'} {instance.title}",
AttributeError: 'ResourceBase' object has no attribute 'is_target'
```
 after deleting the bad dataset function was working as expected, for me.

**Comment by specka** [comment]
@mwallschlaeger You need to provide more information of what command was tried to execute in the API. I do not know, where to put the --filter command. After dataset list?

**Comment by mwallschlaeger** [comment]
please try like that:
`geonodectl tkeywordlabels list --filter "label=Asia"`

**Comment by specka** [comment]
Tested today. Filter function worked, but is still case sensitive. But this issue will be addressed here: https://github.com/GeoNodeUserGroup-DE/geonode-agrovoc-importer/issues/3
